# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[2, 3, 4], [3, 4, 5]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[4, 5, 6], [5, 6, 7], [6, 7, 8]])

a1, a2, a3

(array([1, 2, 3]),
 array([[2, 3, 4],
        [3, 4, 5]]),
 array([[4, 5, 6],
        [5, 6, 7],
        [6, 7, 8]]))

In [3]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (3, 3))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [5]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [6]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((3, 3), 2, dtype('int64'), 9, numpy.ndarray)

In [7]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(a3)
df

0  1  2
0  4  5  6
1  5  6  7
2  6  7  8

In [8]:
# Create an array of shape (10, 2) with only ones
ones = np.ones(shape=(10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros(shape=(7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [15]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0, 100, 3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [17]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(10, size=(7, 2))
random_array

array([[9, 5],
       [9, 8],
       [0, 3],
       [5, 5],
       [4, 7],
       [6, 8],
       [0, 1]])

In [21]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_floats = np.random.random(size=(3, 5)) # or use np,random.random_sample(size=(3, 5))
random_floats

array([[0.24814055, 0.48058846, 0.16994502, 0.75425553, 0.21421292],
       [0.19599158, 0.29498684, 0.60322828, 0.12826143, 0.16789856],
       [0.22315686, 0.35188702, 0.22976025, 0.45115535, 0.34632884]])

In [24]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_nums = np.random.randint(1, 10, size=(4, 6))
random_nums

array([[7, 4, 8, 5, 7, 3],
       [7, 8, 5, 4, 8, 8],
       [3, 6, 5, 2, 8, 6],
       [2, 5, 1, 6, 9, 1]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

Answer: the static random seed value ensures that the same random numbers are generated each time. Useful for sharing work and repropducing random data.

In [28]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
randys = np.random.randint(1, 11, size=(3, 7))

# Find the unique numbers in the array you just created
np.unique(randys)

array([ 1,  2,  3,  5,  6,  7,  8,  9, 10])

In [31]:
# Find the 0'th index of the latest array you created
randys

array([[10,  7, 10,  9,  7,  9,  8],
       [ 2,  1,  7,  7,  8,  5,  3],
       [ 8,  6,  3,  1,  3,  5,  3]])

In [32]:
randys[0]

array([10,  7, 10,  9,  7,  9,  8])

In [33]:
# Get the first 2 rows of latest array you created
randys[:2]

array([[10,  7, 10,  9,  7,  9,  8],
       [ 2,  1,  7,  7,  8,  5,  3]])

In [34]:
# Get the first 2 values of the first 2 rows of the latest array
randys[:2, :2]

array([[10,  7],
       [ 2,  1]])

In [47]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
randoms = np.random.randint(0, 10, size=(3, 5))
ones_array = np.ones((3, 5))

randoms, ones_array

(array([[8, 3, 0, 3, 0],
        [4, 3, 7, 7, 6],
        [2, 0, 0, 2, 5]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [48]:
# Add the two arrays together
np.add(randoms, ones_array)

array([[9., 4., 1., 4., 1.],
       [5., 4., 8., 8., 7.],
       [3., 1., 1., 3., 6.]])

In [49]:
# Create another array of ones of shape (5, 3)
new_ones = np.ones((5, 3))

In [50]:
# Try add the array of ones and the other most recent array together
# np.add(ones_array, new_ones)

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

Answer: Transpose the newest array so it's shape matches the original `ones_array`

In [52]:
# Create another array of ones of shape (3, 5)
other_ones = np.ones((3, 5))

In [61]:
# Subtract the new array of ones from the other most recent array
np.subtract(randoms, other_ones)

array([[ 7.,  2., -1.,  2., -1.],
       [ 3.,  2.,  6.,  6.,  5.],
       [ 1., -1., -1.,  1.,  4.]])

In [62]:
# Multiply the ones array with the latest array
np.multiply(randoms, other_ones)

array([[8., 3., 0., 3., 0.],
       [4., 3., 7., 7., 6.],
       [2., 0., 0., 2., 5.]])

In [63]:
# Take the latest array to the power of 2 using '**'
randoms ** 2

array([[64,  9,  0,  9,  0],
       [16,  9, 49, 49, 36],
       [ 4,  0,  0,  4, 25]])

In [64]:
# Do the same thing with np.square()
np.square(randoms)

array([[64,  9,  0,  9,  0],
       [16,  9, 49, 49, 36],
       [ 4,  0,  0,  4, 25]])

In [65]:
# Find the mean of the latest array using np.mean()
np.mean(randoms)

3.3333333333333335

In [66]:
# Find the maximum of the latest array using np.max()
np.max(randoms)

8

In [67]:
# Find the minimum of the latest array using np.min()
np.min(randoms)

0

In [68]:
# Find the standard deviation of the latest array
np.std(randoms)

2.674987019698517

In [69]:
# Find the variance of the latest array
np.var(randoms)

7.155555555555554

In [70]:
# Reshape the latest array to (3, 5, 1)
np.reshape(randoms, (3, 5, 1))

array([[[8],
        [3],
        [0],
        [3],
        [0]],

       [[4],
        [3],
        [7],
        [7],
        [6]],

       [[2],
        [0],
        [0],
        [2],
        [5]]])

In [71]:
# Transpose the latest array
randoms.T

array([[8, 4, 2],
       [3, 3, 0],
       [0, 7, 0],
       [3, 7, 2],
       [0, 6, 5]])

What does the transpose do?

Answer: switches the axis (reverses the shape)

In [72]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
first_array = np.random.randint(0, 10, size=(3, 3))
second_array = np.random.randint(0, 10, size=(3, 2))

first_array, second_array

(array([[6, 5, 5],
        [5, 2, 5],
        [7, 1, 4]]),
 array([[0, 0],
        [4, 2],
        [3, 2]]))

In [73]:
first_array.shape, second_array.shape

((3, 3), (3, 2))

In [74]:
# Perform a dot product on the two newest arrays you created
np.dot(first_array, second_array)

array([[35, 20],
       [23, 14],
       [16, 10]])

In [75]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
third_array = np.random.randint(0, 10, size=(4, 3))
fourth_array = np.random.randint(0, 10, size=(4, 3))

third_array, fourth_array

(array([[0, 0, 4],
        [5, 2, 8],
        [4, 7, 0],
        [4, 2, 0]]),
 array([[3, 4, 6],
        [0, 2, 1],
        [8, 9, 5],
        [9, 2, 7]]))

In [76]:
third_array.shape, fourth_array.shape

((4, 3), (4, 3))

In [78]:
# Perform a dot product on the two newest arrays you created
# np.dot(third_array, fourth_array)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

Answer: transpose one of the arrays so that the shape satisfies the rules for matrix multiplication (inside numbers match to produce shape of outside numbers)

In [80]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(third_array, fourth_array.T)

array([[ 24,   4,  20,  28],
       [ 71,  12,  98, 105],
       [ 40,  14,  95,  50],
       [ 20,   4,  50,  40]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [81]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
fifth_array = np.random.randint(0, 10, size=(3, 5))
sixth_array = np.random.randint(0, 10, size=(3, 5))

fifth_array, sixth_array

(array([[7, 1, 5, 6, 1],
        [9, 1, 9, 0, 7],
        [0, 8, 5, 6, 9]]),
 array([[6, 9, 2, 1, 8],
        [7, 9, 6, 8, 3],
        [3, 0, 7, 2, 6]]))

In [82]:
# Compare the two arrays with '>'
fifth_array > sixth_array

array([[ True, False,  True,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True,  True]])

What happens when you compare the arrays with `>`?

Answer: the comparisons happen element-wise, so each element in the first array is compared with the corresponding element from the second array.

In [83]:
# Compare the two arrays with '>='
fifth_array >= sixth_array

array([[ True, False,  True,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True,  True]])

In [84]:
# Find which elements of the first array are greater than 7
fifth_array > 7

array([[False, False, False, False, False],
       [ True, False,  True, False, False],
       [False,  True, False, False,  True]])

In [86]:
# Which parts of each array are equal? (try using '==')
fifth_array == sixth_array

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [88]:
# Sort one of the arrays you just created in ascending order
fifth_array.sort()
fifth_array

array([[1, 1, 5, 6, 7],
       [0, 1, 7, 9, 9],
       [0, 5, 6, 8, 9]])

In [89]:
# Sort the indexes of one of the arrays you just created
np.argsort(sixth_array)

array([[3, 2, 0, 4, 1],
       [4, 2, 0, 3, 1],
       [1, 3, 0, 4, 2]])

In [90]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(fifth_array)

8

In [91]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(sixth_array)

11

In [92]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.max(fifth_array, axis=1)

array([7, 9, 9])

In [93]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.min(sixth_array, axis=0)

array([3, 0, 2, 1, 3])

In [100]:
# Create an array of normally distributed random numbers
distributed = np.random.uniform(0, 10, size=(1, 10))
distributed

array([[9.69536867, 7.14595104, 0.41067517, 3.98820901, 4.33520738,
        7.44042643, 2.50860527, 1.84333674, 0.80872967, 4.28314475]])

In [101]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.array(range(1, 100, 2))

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.

### Save NumPy array to CSV

In [103]:
ints = np.random.randint(0,10, size=(3, 7))
ints

array([[0, 9, 9, 0, 1, 5, 8],
       [7, 4, 0, 6, 4, 5, 6],
       [2, 9, 2, 4, 5, 8, 4]])

In [104]:
np.savetxt('random-numpy-ints.csv', ints, delimiter=',')

In [117]:
ls | grep 'random-numpy-ints'

random-numpy-ints.csv
